### ISSUE TITLE
[BUG] cuda out of memory with bs=1

### ISSUE THREAD

**Issue by FelixJiang1998** [AnyaCoder/Bert-VITS2#1]
The output is 
`现在的[BS,LI,EI,epochs,lr,keep]:  [1, 200, 1000, 1000, 0.0003, 5]
config.json文件已更新
终止训练！
python train_ms.py -m /mnt/f/Research/new_bert-vits/Bert-VITS2/logs/base_cj -c ./configs/config.json
开启训练成功！
 http://127.0.0.1:8000
2023-10-20 16:22:54.368 | INFO     | data_utils:_filter:60 - Init dataset...
100%|████████████████████████████████████████████████████████████████████████████████████████| 18397/18397 [00:11<00:00, 1575.08it/s]
2023-10-20 16:23:06.049 | INFO     | data_utils:_filter:75 - skipped: 15, total: 18397
2023-10-20 16:23:06.060 | INFO     | data_utils:_filter:60 - Init dataset...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 956.18it/s]
2023-10-20 16:23:06.064 | INFO     | data_utils:_filter:75 - skipped: 0, total: 4
/home/felixj/miniconda3/envs/voice/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
INFO:base_cj:Loaded checkpoint '/mnt/f/Research/new_bert-vits/Bert-VITS2/logs/base_cj/DUR_0.pth' (iteration 1)
INFO:base_cj:Loaded checkpoint '/mnt/f/Research/new_bert-vits/Bert-VITS2/logs/base_cj/G_0.pth' (iteration 1)
INFO:base_cj:Loaded checkpoint '/mnt/f/Research/new_bert-vits/Bert-VITS2/logs/base_cj/D_0.pth' (iteration 1)
0it [00:00, ?it/s][W reducer.cpp:1346] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/mnt/f/Research/new_bert-vits/Bert-VITS2/mel_processing.py:83: FutureWarning: Pass sr=44100, n_fft=2048, n_mels=128, fmin=0.0, fmax=None as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel = librosa_mel_fn(sampling_rate, n_fft, num_mels, fmin, fmax)
/home/felixj/miniconda3/envs/voice/lib/python3.10/site-packages/torch/functional.py:650: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:863.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/home/felixj/miniconda3/envs/voice/lib/python3.10/site-packages/torch/autograd/__init__.py:251: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [1, 9, 96], strides() = [19680, 96, 1]
bucket_view.sizes() = [1, 9, 96], strides() = [864, 96, 1] (Triggered internally at ../torch/csrc/distributed/c10d/reducer.cpp:320.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
INFO:base_cj:Train Epoch: 1 [0%]
INFO:base_cj:[1.826715350151062, 5.176648139953613, 9.094552040100098, 25.080955505371094, 5.006348609924316, 0.3365189731121063, 0, 0.0003]
INFO:base_cj:Saving model and optimizer state at iteration 1 to /mnt/f/Research/new_bert-vits/Bert-VITS2/logs/base_cj/G_0.pth
INFO:base_cj:Saving model and optimizer state at iteration 1 to /mnt/f/Research/new_bert-vits/Bert-VITS2/logs/base_cj/D_0.pth
INFO:base_cj:Saving model and optimizer state at iteration 1 to /mnt/f/Research/new_bert-vits/Bert-VITS2/logs/base_cj/DUR_0.pth
43it [00:41,  1.04it/s]
Traceback (most recent call last):
  File "/mnt/f/Research/new_bert-vits/Bert-VITS2/train_ms.py", line 638, in <module>
    run()
  File "/mnt/f/Research/new_bert-vits/Bert-VITS2/train_ms.py", line 266, in run
    train_and_evaluate(
  File "/mnt/f/Research/new_bert-vits/Bert-VITS2/train_ms.py", line 443, in train_and_evaluate
    scaler.scale(loss_gen_all).backward()
  File "/home/felixj/miniconda3/envs/voice/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/felixj/miniconda3/envs/voice/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`

And as shown in the outputs, the batch size was set to 1 and the whole project is running on 13700k+4090(24g). Therefore, I think there might be some bugs in the code.

If you need further infomation, welcome to contact.

**Comment by AnyaCoder** [comment]
感觉可能是你的python和pytorch版本的问题，推荐你下载python=3.11.5 , 以及以下版本的pytorch
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

**Comment by FelixJiang1998** [comment]
你好，使用的python版本是3.10，cuda118。不应该会爆显存？祝好，FOn Oct 20, 2023, at 20:47, spicysama ***@***.***> wrote:﻿
感觉可能是你的python和pytorch版本的问题，推荐你下载python=3.11.5 , 以及以下版本的pytorch
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

**Comment by AnyaCoder** [comment]
> 你好，使用的python版本是3.10，cuda118。不应该会爆显存？祝好，FOn Oct 20, 2023, at 20:47, spicysama ***@***.***> wrote:﻿ 感觉可能是你的python和pytorch版本的问题，推荐你下载python=3.11.5 , 以及以下版本的pytorch pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by FelixJiang1998** [comment]
尝试使用3.11.5+cu118还是一样的问题，底模使用的是fishaudio的cj底模，是这个底模太大了吗？

**Comment by FelixJiang1998** [comment]
FIXED - 跟版本无关，确定是Linux问题，可能wsl还是比较有缺陷，用windows完全正常。
